"""Field metadata and fixed-value rules."""

from typing import Dict, Set

SRC_VALUES: Set[str] = {
    "MED",
    "PMC",
    "AGR",
    "ETH",
    "PPR",
    "CTX",
    "NBK",
    "CBA",
    "HIR",
    "PAT",
}

ACCESSION_TYPE_VALUES: Set[str] = {
    "alphafold",
    "arrayexpress",
    "bia",
    "biomodels",
    "bioproject",
    "biosample",
    "biosamples",
    "biostudies",
    "brenda",
    "cath",
    "cellosaurus",
    "chebi",
    "chembl",
    "complexportal",
    "dbgap",
    "doi",
    "ebisc",
    "ega",
    "efo",
    "emdb",
    "empiar",
    "ensembl",
    "eudract",
    "eva",
    "gca",
    "gen",
    "geo",
    "gisaid",
    "go",
    "hgnc",
    "hipsci",
    "hpa",
    "igsr",
    "intact",
    "interpro",
    "metabolights",
    "mint",
    "nct",
    "omim",
    "orphadata",
    "pdb",
    "pfam",
    "pxd",
    "reactome",
    "refseq",
    "refsnp",
    "rfam",
    "rhea",
    "rnacentral",
    "rrid",
    "treefam",
    "uniprot",
}

ANNOTATION_TYPE_VALUES: Set[str] = {
    "Chemicals",
    "Diseases",
    "Experimental Methods",
    "Gene Disease Relationship",
    "Gene Ontology",
    "Gene_Proteins",
    "Organisms",
    "Body-Site",
    "Date",
    "Ecoregion",
    "Engineered",
    "Gene",
    "Host",
    "Kit",
    "LCM",
    "LS",
    "Place",
    "Primer",
    "Sample-Material",
    "Sequencing",
    "Site",
    "State",
    "Treatment",
}

AUTHOR_ROLE_VALUES: Set[str] = {
    "Conceptualization",
    "Data curation",
    "Formal analysis",
    "Funding acquisition",
    "Investigation",
    "Methodology",
    "Project administration",
    "Resources",
    "Software",
    "Supervision",
    "Validation",
    "Visualization",
    "Writing - original draft",
    "Writing - review & editing",
}

LANGUAGE_VALUES: Set[str] = {
    "Afrikaans",
    "Albanian",
    "Arabic",
    "Armenian",
    "Azeri",
    "Bosnian",
    "Bulgarian",
    "Catalan",
    "Chinese",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Esperanto",
    "Estonian",
    "Finnish",
    "French",
    "Gaelic",
    "Georgian",
    "German",
    "Greek",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Italian",
    "Japanese",
    "Kinyarwanda",
    "Korean",
    "Latin",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Malay",
    "Malayalam",
    "Maori",
    "Norwegian",
    "Persian",
    "Polish",
    "Portuguese",
    "Pushto",
    "Romanian",
    "Russian",
    "Serbo-Croatian",
    "Serbo-Croatian (Cyrillic)",
    "Serbo-Croatian (Roman)",
    "Slovak",
    "Slovenian",
    "Spanish",
    "Swedish",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Ukranian",
    "Vietnamese",
}

LICENSE_CANONICAL_VALUES: Set[str] = {
    "CC",
    "CC0",
    "CC-BY",
    "CC-BY-SA",
    "CC-BY-ND",
    "CC-BY-NC",
    "CC-BY-NC-ND",
    "CC-BY-NC-SA",
}

LANGUAGE_CODE_ALIASES: Dict[str, str] = {
    "eng": "English",
    "fre": "French",
    "ukr": "Ukrainian",
}

EPMC_FIELD_DESCRIPTIONS: Dict[str, str] = {
    "ABSTRACT": "Limit search to abstracts",
    "ACCESSION_ID": "Search by data accession number or data DOI mentioned in article text or supplementary files (text-mined)",
    "ACCESSION_TYPE": "Search by linked data resource type such as arrayexpress, biosample, doi, eudract, pdb, pfam, refseq, refsnp, rrid, or uniprot",
    "ACK_FUND": "Search within acknowledgements and funding section of full text records",
    "AFF": "Search by affiliation of authors or collaborators",
    "ANNOTATION_TYPE": "Search by biological entity type found via text mining (Chemicals, Diseases, Gene_Proteins, Organisms, etc.)",
    "APPENDIX": "Search within appendix section of full text records",
    "ARXPR_PUBS": "Show publications with links to given ArrayExpress ID",
    "AUTH": "Search for a surname and optional initials in publication author lists",
    "AUTHORID": "Search by author ORCID identifier",
    "AUTHORID_TYPE": "Search by author ID type (e.g., ORCID)",
    "AUTHOR_ROLES": "Search by CRediT author contribution role; only a limited number of journals currently provide this metadata",
    "AUTH_COLLECTIVE_LIST": "Search by author collective or corporate author group name",
    "AUTH_CON": "Search within author contribution section of full text records",
    "AUTH_FIRST": "Search for an author appearing first in the author list; may provide unexpected results for co-first authors",
    "AUTH_LAST": "Search for an author appearing last in the author list; may provide unexpected results for co-last authors",
    "AUTH_MAN": "Search for author manuscripts submitted via PMC or Europe PMC Manuscript Submission System",
    "AUTH_MAN_ID": "Find an article by specifying a manuscript submission ID",
    "BODY": "Search within the body of a full text article, excluding references",
    "BOOK_ID": "Search by NCBI Bookshelf book identifier (NBK)",
    "CASE": "Search within case study section of full text records",
    "CITED": "Search for publications that have been cited N times",
    "CITES": "Search for records citing a specific record (format: CITES:identifier_source, e.g., CITES:IND43783977_agr)",
    "CHEBI_PUBS": "Show publications with links to given ChEBI ID",
    "CHEBITERM": "Search by ChEBI chemical entity term (text-mined from full text)",
    "CHEM": "Search by MeSH substance",
    "COMP_INT": "Search within competing interests section of full text records",
    "CONCL": "Search within conclusion section of full text records",
    "CREATION_DATE": "Search for publications by date of entry into the Europe PMC database (YYYY-MM-DD or range)",
    "DATA_AVAILABILITY": "Search within data availability section of full text records",
    "DISEASE": "Search by disease name (text-mined from full text)",
    "DISCUSS": "Search within discussion section of full text records",
    "DOI": "Search by one DOI",
    "ED": "Search for book by editor",
    "EMBARGO_DATE": "Search by embargo date (when full text becomes available in Europe PMC)",
    "EMBARGOED_MAN": "Search for currently embargoed author manuscripts (Y/N, translates to EMBARGO_DATE range)",
    "EMBL_PUBS": "Show publications with links to given EMBL ID",
    "EPMC_AUTH_MAN": "Search for author manuscripts submitted via Europe PMC Manuscript Submission System",
    "ESSN": "Search by one ESSN",
    "EXT_ID": "Search by external source ID combined with source (format: EXT_ID:identifier AND SRC:source)",
    "E_PDATE": "Search by electronic publication date (when first published online, supports [YYYY TO YYYY] range)",
    "FIG": "Search within figure titles and legends of full text records",
    "FIRST_IDATE": "Search by date record was first indexed in Europe PMC",
    "FIRST_PDATE": "Search by first publication date (electronic or print, supports range)",
    "GENE_PROTEIN": "Search by Gene or Protein name (text-mined from full text)",
    "GOTERM": "Search by Gene Ontology term (text-mined from full text)",
    "GRANT_AGENCY": "Search by funding grant agency that supported the research",
    "GRANT_ID": "Search by grant identifier (use with GRANT_AGENCY)",
    "HAS_ABSTRACT": "Limit search results according to presence or absence of abstract (Y/N)",
    "HAS_ARXPR": "Limit to records with ArrayExpress gene expression data (Y/N)",
    "HAS_BOOK": "Limit search to books and documents from NCBI Bookshelf (Y/N)",
    "HAS_CHEBI": "Limit to records with ChEBI chemical data (Y/N)",
    "HAS_CHEMBL": "Limit to records with ChEMBL small molecule data (Y/N)",
    "HAS_DATA": "Limit search to records that have links to data (Y/N)",
    "HAS_DOI": "Limit search results to those publications which do or do not have a DOI (Y/N)",
    "HAS_EMBL": "Limit to records with EMBL nucleotide data (Y/N)",
    "HAS_FREE_FULLTEXT": "Limit to records with free full text (displayed in Europe PMC or linked via Unpaywall) (Y/N)",
    "HAS_FT": "Limit search results according to availability of fulltext article or book in Europe PMC (Y/N)",
    "HAS_INTACT": "Limit to records with IntAct protein interactions (Y/N)",
    "HAS_INTERPRO": "Limit to records with InterPro protein family data (Y/N)",
    "HAS_LABSLINKS": "Lists articles that have links provided by 3rd parties (Y/N)",
    "HAS_OMIM": "Limit to records with OMIM genetic data (Y/N)",
    "HAS_PDB": "Limit to records with PDB protein structures (Y/N)",
    "HAS_PDF": "Limit search results according to availability of PDF version in Europe PMC (Y/N)",
    "HAS_PREPRINT": "Limit search results to peer reviewed articles which were preceded by a preprint version (Y/N)",
    "HAS_PUBLISHED_VERSION": "Limit search results to preprints which were later peer reviewed, edited, typeset and published (Y/N)",
    "HAS_REFLIST": "Limit search results to only those publications with a reference list (Y/N)",
    "HAS_SUPPL": "List articles that have supplemental data (spreadsheets, video files, etc.) (Y/N)",
    "HAS_TM": "Limit search results to text-mined fulltext articles only (Y/N)",
    "HAS_UNIPROT": "Limit to records with UniProt protein data (Y/N)",
    "HAS_VERSION_EVALUATIONS": "Limit search results to articles where one or more versions has a review or evaluation (Y/N)",
    "HAS_XREFS": "Limit search results to articles with cross-references to other databases (Y/N)",
    "IN_EPMC": "Limit search results according to availability of fulltext article in Europe PMC (Y/N)",
    "IN_PMC": "Limit search results according to availability of fulltext article in PubMed Central (Y/N)",
    "INTRO": "Search within introduction and background section of full text records",
    "INTACT_PUBS": "Show publications with links to given IntAct ID",
    "INTERPRO_PUBS": "Show publications with links to given InterPro ID",
    "INVESTIGATOR": "Search for collaborator/investigator within author collective (use with AUTH_COLLECTIVE_LIST)",
    "ISBN": "Search by one ISBN",
    "ISSN": "Search by one ISSN",
    "ISSUE": "Search by journal issue number; most useful with JOURNAL and VOLUME",
    "JOURNAL": "Search by journal title in full or abbreviated form",
    "KEYWORD": "Search within keywords section of full text records (author or publisher provided)",
    "KW": "Search by keyword, including MeSH and other subject headings",
    "LABS_PUBS": "Search by labs and publications resource ID",
    "LANG": "Search by publication language; the saved help page documents code examples like LANG:eng and LANG:fre",
    "LICENSE": "Search by grouped Creative Commons license family; LICENSE:cc matches any Creative Commons license",
    "METHODS": "Search within materials and methods section of full text records",
    "MESH": "Search by MeSH heading",
    "NIH_AUTH_MAN": "Search for manuscripts submitted via NIH Manuscript Submission System",
    "OPEN_ACCESS": "Limit search to content that Europe PMC treats as open access (generally content with a Creative Commons or similar reuse license) (Y/N)",
    "ORGANISM": "Search by mined organisms (text-mined from full text)",
    "ORG_ID": "Search by Research Organization Registry (ROR) ID for affiliations; currently limited data coverage",
    "OTHER": "Search within other sections of full text records",
    "PDB_PUBS": "Show publications with links to given PDBe ID",
    "PMCID": "Search by one PMCID",
    "PUBLISHER": "Search by publisher name of journal articles or books",
    "PUB_TYPE": "Search by publication type (review, clinical trial, editorial, letter, guideline, etc.)",
    "PUB_YEAR": "Search by year of publication (supports single year or range syntax like [2015 TO 2020])",
    "P_PDATE": "Search by print publication date (when appeared in print, supports range)",
    "REFFED_BY": "Search for records cited by a specific record (format: REFFED_BY:identifier_source)",
    "REF": "Search within references section of full text records only",
    "RESULTS": "Search within results section of full text records",
    "SRC": "Search for articles from a particular repository (MED, PMC, AGR, ETH, PPR, CTX, NBK, etc.)",
    "SUPPL": "Search within supplementary information section of full text records",
    "TABLE": "Search within tables section of full text records",
    "TITLE": "Limit search to article titles",
    "TITLE_ABS": "Limit search to title or abstract combined",
    "UNIPROT_PUBS": "Show publications with links to given UniProt ID",
    "UPDATE_DATE": "Search by date record was updated in Europe PMC",
    "VOLUME": "Search by journal volume number (use with JOURNAL)",
}

VALID_EPMC_FIELDS: Set[str] = set(EPMC_FIELD_DESCRIPTIONS.keys())

FIXED_VALUE_FIELDS: Dict[str, Set[str]] = {
    "SRC": SRC_VALUES,
    "ACCESSION_TYPE": ACCESSION_TYPE_VALUES,
    "LICENSE": LICENSE_CANONICAL_VALUES,
    "LANG": LANGUAGE_VALUES,
    "ANNOTATION_TYPE": ANNOTATION_TYPE_VALUES,
    "AUTHORID_TYPE": {"ORCID"},
    "AUTHOR_ROLES": AUTHOR_ROLE_VALUES,
    "GRANT_AGENCY": set(),
    "GRANT_ID": set(),
}

BOOLEAN_FIELDS: Set[str] = {
    "HAS_ABSTRACT",
    "HAS_ARXPR",
    "HAS_BOOK",
    "HAS_CHEBI",
    "HAS_CHEMBL",
    "HAS_DATA",
    "HAS_DOI",
    "HAS_EMBL",
    "HAS_FREE_FULLTEXT",
    "HAS_FT",
    "HAS_INTACT",
    "HAS_INTERPRO",
    "HAS_LABSLINKS",
    "HAS_OMIM",
    "HAS_PDB",
    "HAS_PDF",
    "HAS_PREPRINT",
    "HAS_PUBLISHED_VERSION",
    "HAS_REFLIST",
    "HAS_SUPPL",
    "HAS_TM",
    "HAS_UNIPROT",
    "HAS_VERSION_EVALUATIONS",
    "HAS_XREFS",
    "OPEN_ACCESS",
    "EPMC_AUTH_MAN",
    "NIH_AUTH_MAN",
    "AUTH_MAN",
    "EMBARGOED_MAN",
    "IN_PMC",
    "IN_EPMC",
}

YEAR_ONLY_DATE_FIELDS: Set[str] = {"PUB_YEAR"}

DATE_FIELDS: Set[str] = {
    "PUB_YEAR",
    "E_PDATE",
    "P_PDATE",
    "UPDATE_DATE",
    "CREATION_DATE",
    "FIRST_PDATE",
    "FIRST_IDATE",
    "EMBARGO_DATE",
}
