#!/bin/bash
# auth: GoTrue (supabase/gotrue). Any other GOTRUE_* variable in .env, such as
# the OAuth, SMS or MFA settings commented out in docker-compose.yml, reaches
# it unchanged.
source "$(dirname "$0")/lib.sh"
log_as auth
wait_for_db

export GOTRUE_API_HOST=127.0.0.1
export GOTRUE_API_PORT=$AUTH_PORT
export API_EXTERNAL_URL

export GOTRUE_DB_DRIVER=postgres
export GOTRUE_DB_DATABASE_URL="postgres://supabase_auth_admin:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
export GOTRUE_DB_MIGRATIONS_PATH=/usr/local/etc/auth/migrations

export GOTRUE_SITE_URL=$SITE_URL
export GOTRUE_URI_ALLOW_LIST=$ADDITIONAL_REDIRECT_URLS
export GOTRUE_DISABLE_SIGNUP=$DISABLE_SIGNUP

export GOTRUE_JWT_ADMIN_ROLES=service_role
export GOTRUE_JWT_AUD=authenticated
export GOTRUE_JWT_DEFAULT_GROUP_NAME=authenticated
export GOTRUE_JWT_EXP=$JWT_EXPIRY
export GOTRUE_JWT_SECRET=$JWT_SECRET
export GOTRUE_JWT_ISSUER=$API_EXTERNAL_URL

export GOTRUE_EXTERNAL_EMAIL_ENABLED=$ENABLE_EMAIL_SIGNUP
export GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED=$ENABLE_ANONYMOUS_USERS
export GOTRUE_MAILER_AUTOCONFIRM=$ENABLE_EMAIL_AUTOCONFIRM

export GOTRUE_SMTP_ADMIN_EMAIL=$SMTP_ADMIN_EMAIL
export GOTRUE_SMTP_HOST=$SMTP_HOST
export GOTRUE_SMTP_PORT=$SMTP_PORT
export GOTRUE_SMTP_USER=$SMTP_USER
export GOTRUE_SMTP_PASS=$SMTP_PASS
export GOTRUE_SMTP_SENDER_NAME=$SMTP_SENDER_NAME
export GOTRUE_MAILER_URLPATHS_INVITE=$MAILER_URLPATHS_INVITE
export GOTRUE_MAILER_URLPATHS_CONFIRMATION=$MAILER_URLPATHS_CONFIRMATION
export GOTRUE_MAILER_URLPATHS_RECOVERY=$MAILER_URLPATHS_RECOVERY
export GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE=$MAILER_URLPATHS_EMAIL_CHANGE

export GOTRUE_EXTERNAL_PHONE_ENABLED=$ENABLE_PHONE_SIGNUP
export GOTRUE_SMS_AUTOCONFIRM=$ENABLE_PHONE_AUTOCONFIRM

exec auth
